Add holder type
kljohann/genpybind-legacy pull request #3
Opened 2018-10-23 11:56 UTC by muffgaga

2018-10-30 18:29 UTC, kljohann requested changes
Thank you for the pull request and sorry that I noticed it just now (I did not get a notification). Some minor comments inline.

2018-10-30 18:29 UTC, kljohann commented on tests/holder_type.cpp
> +  return this->child;
```suggestion
  return child;
```

2018-10-30 18:29 UTC, kljohann commented on tests/holder_type.cpp
> +  return this->child.use_count();
```suggestion
  return child.use_count();
```

2018-10-30 18:29 UTC, kljohann commented on genpybind/decls/klasses.py
> +        self._holder_type.update(patterns)
There can only be a single holder type and using this attribute without arguments should probably be an error. Can you try the following and change the `holder_type` / `statements` functions accordingly?
```python
    def set_holder_type(self, holder_type):
        # type: Optional[Text] -> None
        self._holder_type = holder_type
```

2018-10-30 18:29 UTC, kljohann commented on genpybind/decls/klasses.py
> +        self._holder_type = set()  # type: Set[Text]
```suggestion
        self._holder_type = None  # type: Optional[Text]
```
(see below)

2018-10-30 18:29 UTC, kljohann commented on genpybind/decls/klasses.py
> +        filter_bases = ['std::enable_shared_from_this']
This somewhat duplicates the `hide_base` functionality. Though I agree that we probably always want to hide `enable_shared_from_this`. Can you integrate this into the `bases` function?

2018-10-30 18:29 UTC, kljohann commented on genpybind/decls/klasses.py
> +            classes=", ".join([self.fully_qualified_name] + self.base_specifiers() + list(self.holder_type)),
Maybe add a comment that the order of extra arguments does not matter. As the line is getting rather long, you could also extract this to a variable.

```python
        # Wrapped class has to be specified first; order of extra arguments does not matter
        options = [self.fully_qualified_name] + self.base_specifiers()
        if self.holder_type is not None:
            options.append(self.holder_type)

        # ...

            classes=", ".join(options),
```

2018-10-30 18:29 UTC, kljohann commented on tests/holder_type.h
> +class GENPYBIND(visible, holder_type("std::shared_ptr<Child>")) Child : public std::enable_shared_from_this<Child> {};
Can you run `clang-format` on both `holder_type.h` and `holder_type.cpp`?

2018-10-31 08:33 UTC, muffgaga commented
ACK → @yungwundi, please fix :)

2018-11-06 09:52 UTC, yungwundi commented
@kljohann fixed, hopefully!

2018-11-06 13:13 UTC, muffgaga commented on genpybind/decls/klasses.py
> +        self._hide_base = set(Klass.filter_bases)  # type: Set[Text]
~~@yungwundi can you comment on this change?~~ Did not look at the change in line 29 → ok for me.

2018-11-06 13:13 UTC, muffgaga commented on genpybind/decls/klasses.py
> -
@yungwundi unrelated change?

2018-11-06 13:18 UTC, muffgaga commented on genpybind/decls/klasses.py
> +            classes=", ".join([self.fully_qualified_name] + self.base_specifiers() + list(self.holder_type)),
@yungwundi some additional comment?

2018-11-28 11:20 UTC, muffgaga commented
@kljohann Is anything still open (we did some force pushes and the github review view is a bit suboptimal)?

2018-12-02 19:33 UTC, kljohann approved these changes

2018-12-03 18:57 UTC, kljohann commented on genpybind/decls/klasses.py
> +        # type: Optional[Text] -> None
This has to be `(Optional[Text]) -> None`.

2018-12-03 19:04 UTC, closed without merging

2018-12-03 19:05 UTC, kljohann commented
Merged with minor changes.