Bump to C++17 and test std::optional
kljohann/genpybind-legacy pull request #4
Opened 2018-11-19 15:37 UTC by muffgaga

Should we add a configuration switch for C++17 things like `std::optional`?

2018-11-19 15:37 UTC, muffgaga commented
@obreitwi

2018-11-19 15:38 UTC, muffgaga commented
@phispilger You requested this test...

2018-11-25 17:27 UTC, kljohann requested changes
Thanks for the PR! Some minor comments. Can you make it more clear that the C++17 flags only apply to the tests? For example "Add test for std::optional, bump tests to C++17"?
Can you also change `std=c++14` to `std=c++17` in `tests/genpybind_waf.py`?

2018-11-25 17:27 UTC, kljohann commented on tests/optional_parameters_test.py
> +    assert m.foo() == None
```suggestion
    assert m.foo() is None
```

2018-11-25 17:27 UTC, kljohann commented on tests/optional_parameters_test.py
> +    assert m.foo(None) == None
Please use `is None`.
```suggestion
    assert m.foo(None) is None
```

2018-11-25 17:27 UTC, kljohann commented on tests/optional_parameters_test.py
> +    print dir(m)
Please remove this print statement.
```suggestion
```

2018-11-25 17:27 UTC, kljohann commented on tests/optional_parameters.cpp
> +	return o;
Please clang-format this file using the configuration contained in the repo.

2018-11-28 11:20 UTC, muffgaga commented
@kljohann ACK, will handle → I'll also test-drive on clang7.

2019-01-08 14:11 UTC, muffgaga commented
> @kljohann ACK, will handle → I'll also test-drive on clang7.

clang7 works for me -> @phispilger fixes the other stuff plz

2019-01-10 20:36 UTC, kljohann commented on tests/optional_parameters.h
> +// clang 5 does not support std::optional :(
I think this is not clang's fault but rather is necessary due to the old version of libstdc++ in the CI image. (It's still using gcc 6.3.0.) Maybe that's also what you ran into during your local testing?

2019-01-11 08:45 UTC, muffgaga commented on tests/optional_parameters.h
> +// clang 5 does not support std::optional :(
ACK, and dropped comment → `--gcc-toolchain=` option solves it.

2019-01-23 11:52 UTC, muffgaga commented on tests/optional_parameters.h
> +// clang 5 does not support std::optional :(
And a correct installation of clang (`-DGCC_PREFIX_PATH`) also fixes the build without providing `--gcc-toolchain`.

2019-01-25 16:44 UTC, kljohann approved these changes

2019-01-29 20:49 UTC, closed without merging

2019-01-29 20:50 UTC, kljohann commented
Merged, thanks!