Fix wrapping for pybind11::{,kw}args arguments
kljohann/genpybind-legacy pull request #8
Opened 2018-12-03 15:50 UTC by muffgaga

@kljohann That's just a draft → can you suggest something regarding how to obtain the fully qualified name of the argument in a nicer way (the cutils getter asserts on a list of KINDs where the PARAM type is not included). Regarding test build we could also add some "needs-pyembed" section (maybe extra folder?).

2018-12-03 16:20 UTC, muffgaga commented on genpybind/decls/callables.py
> +            if str(child.type.fully_qualified_name) in ['::pybind11::args', '::pybind11::kwargs']:
There should be a nicer (genpybindy) way to access the fqn…

2018-12-03 16:21 UTC, muffgaga commented on tests/wscript
> +            features="cxx cxxshlib pyembed",
Introduces a dependency for the new test → maybe separate targets for this?

2018-12-03 18:04 UTC, muffgaga commented on tests/argsandkwargs.h
> +#define SYMBOL_VISIBLE __attribute__((visibility("default")))
The free functions ended up as "local" symbols in `libargsandkwargs.so` → `pyargsandkwargs.so` couldn't use them.

2018-12-03 18:05 UTC, muffgaga commented on tests/wscript
> +            linkflags='-Wl,-z,defs',
To break early (during build) if symbols are still missing.

2018-12-03 19:33 UTC, kljohann commented on genpybind/decls/callables.py
> +            if str(child.type.fully_qualified_name) in ['::pybind11::args', '::pybind11::kwargs']:
I only had a cursory look but: Using `child.type.fully_qualified_name` should be okay (it's introduced by one of the libclang patches). It's a string already so you do not need the extra `str`.
I wonder: Are these ever passed by reference?

Maybe we should also add a check that `::pybind11:{kw,}args` are the last arguments to the function as else we will still add `py::arg(...)` for following arguments (but at the position of the `{kw,}args` parameters. → In fact it would even be okay to `break` here.

2018-12-03 19:35 UTC, kljohann commented on tests/argsandkwargs.cpp
> +}
Make sure to also add some tests where `::pybind11::{kw,}args` is combined with other arguments.

2019-01-24 11:35 UTC, muffgaga commented on tests/argsandkwargs.cpp
> +}
ACK

2019-01-24 11:35 UTC, muffgaga commented on genpybind/decls/callables.py
> +            if str(child.type.fully_qualified_name) in ['::pybind11::args', '::pybind11::kwargs']:
> [ str() not needed ]

Ok, will drop.


>  I wonder: Are these ever passed by reference?

At least non-valued usage isn't covered by the existing pybind11 tests:
https://github.com/pybind/pybind11/blob/master/tests/test_kwargs_and_defaults.cpp


> [args, kwargs have to be last]

Adding assert.

2019-01-24 12:25 UTC, muffgaga commented on tests/argsandkwargs.cpp
> +}
done

2019-01-24 12:25 UTC, muffgaga commented on tests/argsandkwargs.cpp
> +}
done

2019-01-24 12:25 UTC, muffgaga commented on genpybind/decls/callables.py
> +            if str(child.type.fully_qualified_name) in ['::pybind11::args', '::pybind11::kwargs']:
btw. there's a static_assert for the args/kwargs position: https://github.com/pybind/pybind11/blob/master/include/pybind11/cast.h#L1894

2019-01-24 12:26 UTC, muffgaga commented
ping :)

2019-01-25 17:27 UTC, kljohann requested changes

2019-01-25 17:27 UTC, kljohann commented on genpybind/decls/callables.py
> +            assert no_args_or_kwargs
I think we should raise an exception here and include an explanation for the user:
```suggestion
            if is_after_args_or_kwargs:
                raise RuntimeError("py::args / py::kwargs cannot be followed by other arguments")
```

2019-01-25 17:27 UTC, kljohann commented on genpybind/decls/callables.py
> +            assert no_args_or_kwargs
I think we should raise an exception here and include an explanation for the user:
```suggestion
            if after_args_or_kwargs:
                raise RuntimeError("py::args / py::kwargs cannot be followed by other arguments")
```

2019-01-25 17:27 UTC, kljohann commented on genpybind/decls/callables.py
> +        no_args_or_kwargs = True
```suggestion
        after_args_or_kwargs = False
```

2019-01-25 17:27 UTC, kljohann commented on tests/wscript
> +            use=["PYBIND11"],
Where do you use this define?

2019-01-28 11:56 UTC, muffgaga commented on tests/wscript
> +            use=["PYBIND11"],
removed

2019-01-28 11:56 UTC, muffgaga commented on genpybind/decls/callables.py
> +            assert no_args_or_kwargs
ACK

2019-01-28 11:56 UTC, muffgaga commented on genpybind/decls/callables.py
> +            assert no_args_or_kwargs
ACK

2019-01-29 14:19 UTC, muffgaga commented
ping?

2019-01-29 20:49 UTC, closed without merging

2019-01-29 20:50 UTC, kljohann commented
Merged, thank you!